### ISSUE TITLE
Escape characters in answers and feedback

### ISSUE THREAD

**Issue by dthies** [dthies/moodle-atto_cloze#10]
The editor should add and remove backslashes so that special characters are automatically escaped when add to the answer and feedback inputs on the form.

**Comment by germanvaleroelizondo** [comment]
I just managed to produce another error when trying to use escaped characters as in https://en.wikipedia.org/wiki/Escape_character :

![cloze_editor_error_missingcourseorcmid](https://cloud.githubusercontent.com/assets/2671923/17977245/86098ee2-6ab6-11e6-9209-48a72d2d9e05.png).

.. But now I can not reproduce the error :( I will keep on trying...

**Comment by dthies** [comment]
German, try the new version I just pushed. It should handle special characters correctly.

**Comment by germanvaleroelizondo** [comment]
Hi Daniel,
I was using version     2016073100 . I will download the newest version right now

**Comment by germanvaleroelizondo** [comment]
Now testing  plugin version 2016073102 ...

**Comment by germanvaleroelizondo** [comment]
Hi Daniel.
If the user writes as answer Grant's zebra it displays correctly,
but if the user writes Grant\'s zebra it displays as Grant\'s zebra with a double backslash (but this GitHub editor will now remove the double backslash). Please see image below:

![double backslash](https://cloud.githubusercontent.com/assets/2671923/17979436/2fa9c33c-6ac0-11e6-944e-8c0d3a4bd79b.png)

Is that the expected behaviour?

**Comment by dthies** [comment]
Yes, I believe that is correct. The characters that need to be escaped are the ones used to delimiter the parts of the cloze question namely #, ~, and  }. These have to have a \ added to prevent them from being interpreted as terminating the field. The backslash also has to be escaped if you want it to be displayed instead of used as escape sequence.
The way to check the behaviour is to type those characters into an answer or feedback blank, insert, save question, and preview. The question preview should match whatever the user typed in the form. The escape sequence should only appear in the main atto editor.

**Comment by dthies** [comment]
German, you did find a problem. The backslash is not suppose to be escaped in this case. Only #, ~, and } are to be escaped. I fixed that and will update the version in the database now.
