### ISSUE TITLE
Parsing method crashes in IE 11

### ISSUE THREAD

**Issue by dthies** [dthies/moodle-atto_cloze#15]
This was reported in the Moodle forum https://moodle.org/mod/forum/discuss.php?d=337286#p1368531. Console complains .contains is not supported on node.

**Comment by germanvaleroelizondo** [comment]
It also happens with IE 8 and with Safari 5.1.7 for Windows.

Firefox (48.0.2), Google Chrome (Versión 55.0.2858.0 canary 64-bit) and Opera (39.0) work as expected.

**Comment by dthies** [comment]
Thanks German.
I think I have it fixed now.

**Comment by germanvaleroelizondo** [comment]
New version fixed issue in IE and Safari :)
Thanks Daniel.
When can you update the Moodle plugins database ZIP file?

**Comment by germanvaleroelizondo** [comment]
It seems you already have updated the Moodle plugins database.
Thanks.
