### ISSUE TITLE
sporadically next cloze answers are copied from previus ones

### ISSUE THREAD

**Issue by Canx** [dthies/moodle-atto_cloze#18]
It happens from time to time, answers made to previous questions are copied when creating news ones, instead of being empty.

As an example for replicating this bug try to copy this:

```
>{1:SHORTANSWER:~%100%enable}
# {1:SHORTANSWER:~%100%conf~%100%configure} term
(config)#vlan 2
(config-vlan)#name marketing
```

and then add a new cloze shortanswer selecting the word "term" in the second line.

NOTE: my current version is from github (2016111500)

**Comment by dthies** [comment]
It took a little time for me to find how to reproduce this consistently.  It appears for me in Firefox in I select the word by double clicking, but not if I click and drag. I apparently made a invalid assumption about the the way the selection is represented in the browser. I am busy with other projects at the moment, but will fix it when I am free.
