### ISSUE TITLE
When using a multichoice option, if the user inserts many options, the screen grows taller, but without scroll bars the user can not click on the 'Insert' button.

### ISSUE THREAD

**Issue by germanvaleroelizondo** [dthies/moodle-atto_cloze#2]
When using a multichoice option, if the user inserts many options, the screen grows taller, but without scroll bars the user can not click on the 'Insert' button. See enclose image

![cloze for atto no scroll buttons for excessivelly tall popup windowo](https://cloud.githubusercontent.com/assets/2671923/17154972/e3bcfd92-5348-11e6-9ce6-f0a31bf77099.png)

**Comment by dthies** [comment]
I was not able to reproduce this with firefox on ubuntu. The browser still scrolled for me, but I added a scrollbar to the answer block.

**Comment by germanvaleroelizondo** [comment]
Thanks Daniel.
I saw it in firefox in a Windows 7 Moodle 3.1+ complete package install.

**Comment by germanvaleroelizondo** [comment]
I will download a new Moodle 3.1.1- Windows complete package and re-test with the fresh plugin version within the hour.

**Comment by germanvaleroelizondo** [comment]
I just tested a new version of the plugin and it works beautifully.

**Comment by dthies** [comment]
Great!
