### ISSUE TITLE
Lack of spacing with 3.8DEV 

### ISSUE THREAD

**Issue by germanvaleroelizondo** [dthies/moodle-atto_cloze#24]
![Cloze question issue 01](https://user-images.githubusercontent.com/2671923/66934240-cd34cf80-efff-11e9-95f1-d5637a41b600.png)
Hi Daniel,

I have been testing this and other plugins with the Moodle 3.8dev+ (Build: 20191016) branch.

In both Classic and Boost themes, the options show too close to the selection buttons, which looks ugly.

The same problem happens with the TinyMCE plugin for cloze.
I think it is a Moodle core issue.

Moodle 3.1 was the last branch that had a proper spacing.

This lack of spacing  happens with all Moodle branches from 3.2 to 3.8DEV

**Comment by dthies** [comment]
Hi German,

Yes this really is core or theme issue (specifically Boost, Classic inherits CSS from Boost). There was some CSS in the older standard theme that adjusted the styling of quiz and questions that were not carried to Boost. There are some styling fixes for multichoice, but not cloze. It can be corrected by adding  to custom CSS or preset file
`.que.multianswer .answer label {
    padding: 0 .3em;
}`
It is not really an issue with this plugin or with the quiz mod per se.

**Comment by germanvaleroelizondo** [comment]
Thanks for the explanation Daniel.
Would you think it merits the creation of a Moodle tracker issue?
