### ISSUE TITLE
Button not appearing on moodle atto

### ISSUE THREAD

**Issue by ocimjr** [dthies/moodle-atto_cloze#25]
Even after adding cloze = cloze on this page (admin/settings.php?section=editorsettingsatto). Not a sign of button.

The only thing I saw, is that this required moodle-tinymce_cloze-editor. And this is not found.

Moodle is currently on version 3.8.3. 
editor_atto is on 2019111800
atto_cloze is on 1.1 - 2017072802

Thank you

**Comment by germanvaleroelizondo** [comment]
Have you chosen Atto at the highest position in your user preferences for editor?

There is an older, similar plugin for the same goal for the TinyMCE editor.

You can have several editors available in a Moode server, but you need to choose one (at the top of the list) as your default editor.

**Comment by ocimjr** [comment]
The problem is with atto. 
Atto is in the highest position in our list (accessible on admin/settings.php?section=manageeditors).
I looked all the questions, unfortunately none solve the problem.

**Comment by germanvaleroelizondo** [comment]
I just tested (OK) in  Moodle 39devplus (Build 20200522).jpg

![imagen](https://user-images.githubusercontent.com/2671923/83458238-c68c8880-a427-11ea-8c38-a360c1150ea0.png)

**Comment by germanvaleroelizondo** [comment]
In Moodle 3.8.2 (build 20200327) OK

![imagen](https://user-images.githubusercontent.com/2671923/83458738-a0b3b380-a428-11ea-9a14-b95d3e34d7eb.png)

**Comment by germanvaleroelizondo** [comment]
Are you sure you are choosing to create an Embedded answers (Cloze) question type ?

![imagen](https://user-images.githubusercontent.com/2671923/83458852-df496e00-a428-11ea-9c80-57f780d3c985.png)

**Comment by ocimjr** [comment]
Thank you for your answer. Maybe I'm not aware of how it function. 
So, atto button will only appear if you choose a question "Embedded answers (Cloze)"?
We thought button will always appear
