### ISSUE TITLE
Great usability addition

### ISSUE THREAD

**Issue by germanvaleroelizondo** [dthies/moodle-atto_cloze#3]
The plugin looks great so far, but I think it will be a lot easier to use for novice Moodler if you added some **help inside the popup window of the cloze editor itself**. This help will link to Moodle Docs page https://docs.moodle.org/31/en/Embedded_Answers_(Cloze)_question_type#Format . The Documemntation page, of course, must be updated and match the different buttons options.

I think that this link (button or text hyperlink) would be even better if it was a variable string, which can be translated in AMOS. For example, the spanish translationfor this string in AMOS might be https://docs.moodle.org/all/es/Tipo_de_Pregunta_con_respuestas_incrustadas_(Cloze)#Formato . The text 'HELP' must also be an AMOS translatable English language string.

![cloze for atto question types choices with help link](https://cloud.githubusercontent.com/assets/2671923/17156317/cb1e3b38-534e-11e6-92bc-8c7d78c15986.png)

**Comment by dthies** [comment]
Yes, I think this needs to be redone. I intended to recreate something similar to the activity or question choosers which would give the option and an explanation of the question type.

**Comment by germanvaleroelizondo** [comment]
These are very good news Daniel. 

Better than my original suggestion and a very user-friendly improvement. The only problem I foresee is that you will have to write the explanations for all the available question types as AMOS-friendly English string variables. 

I think that you have to decide whether the names of the available question types themselves (inside the buttons) will be hard-wired ALL CAPITALS string constants, as per cloze current syntax (as seen in the above screen image), or AMOS-friendly string variables.

I guess that many non-tech-oriented Moodle teachers would find it a lot easier to choose an option written with a plain-language name (either English or translation) as opposed to the ALL-CAPITAL syntax-true constant name.

And, to make it really best for all users (except the programmer), you can include a configuration option for the plugin, where the user can choose either TRUE-CLOZE-SYNTAX or user-friendly string-variable names for the buttons (this last option would be my preferred default setting).

**Comment by dthies** [comment]
I need a little more work to make this look like the standard question chooser now, but it should be better.

**Comment by germanvaleroelizondo** [comment]
I will be looking forward to your next version of this plugin.

In the meantime, I will try to write some more Moodle documentation and insert screengrabs.

Thanks.

**Comment by germanvaleroelizondo** [comment]
I just updated the cloze plugin from version 2015041601     to 2015041602.
 I will report soon.

**Comment by germanvaleroelizondo** [comment]
It is working very nicely. I had forgotten to change my  text server language into English and it showed me the Mexican Spanish description of the available question types. GREAT. Excellent work Daniel.

![atto cloze editor available question types](https://cloud.githubusercontent.com/assets/2671923/17179723/d46e4f3e-53df-11e6-9997-27f2dde3ec2a.png)

**Comment by germanvaleroelizondo** [comment]
But, when I pressed the 'Cancel' button in the above screen, I got an error message. Is this the expected behaviour?

![error when choosing cancel while selecting atto cloze editor available question types](https://cloud.githubusercontent.com/assets/2671923/17179869/53fcf638-53e0-11e6-9e14-f9a6d37a197c.png)

**Comment by dthies** [comment]
I need to fix that

**Comment by germanvaleroelizondo** [comment]
I can confirm that the question types descriptions also work in the German language. I presume that they will work in all AMOS translated languages. GREAT.

![deutch atto cloze editor available question types](https://cloud.githubusercontent.com/assets/2671923/17180322/aa5f3a94-53e1-11e6-85d9-b2ed129c4180.png)

**Comment by germanvaleroelizondo** [comment]
And in the French language. This is really very good for worldwide Moodle users.

![french atto cloze editor available question types](https://cloud.githubusercontent.com/assets/2671923/17180437/1966c2a4-53e2-11e6-908d-52bcf8266577.png)

**Comment by germanvaleroelizondo** [comment]
I created the Moodle Docs page at https://docs.moodle.org/31/en/error/question/missingcourseorcmid 

Please feel free to add or correct as needed.

I simply can't guess what a missing course or cm id is.

**Comment by germanvaleroelizondo** [comment]
With the most recent plugin version (same version number as before), the error that happened when pressing the 'Cancel' button no longer appears. :)

**Comment by dthies** [comment]
I redid the chooser so that it is closer to the behaviour for adding standard question types.

**Comment by germanvaleroelizondo** [comment]
The newer version is leaner, cleaner and very user-friendly:

![new cloze edito for atto popup window](https://cloud.githubusercontent.com/assets/2671923/17215875/05a3095e-54a4-11e6-9990-bc60462dd21c.png)

**Comment by germanvaleroelizondo** [comment]
I ran into a problem.

I intended to write one cloze question that used all the available question types, so as to use the resulting images for the documentation.

The making of the first question type went perfect.

But when I try to edit the second sentence to add a new cloze question type, the editor returns me to the previously made question. I thought that maybe I needed to save my progress and continue editing (which I did, but did not help)...

 I found this behaviour odd:

![new cloze edito for atto popup window not able to do second question](https://cloud.githubusercontent.com/assets/2671923/17216410/29e94cb8-54a6-11e6-8765-6c2fffbf3f84.png)

**Comment by germanvaleroelizondo** [comment]
So, I selected the text I want to use for the second question type example:

![new cloze edito for atto now i want to make the second question type](https://cloud.githubusercontent.com/assets/2671923/17216515/9ab7552a-54a6-11e6-9515-9dbc501b37c5.png)

**Comment by germanvaleroelizondo** [comment]
But when I click on the cloze editor button, the plugin shows me the first question I had made before, not the new text I wanted for my second question example:

![new cloze edito for atto but the plugin shows me again the first question i made before](https://cloud.githubusercontent.com/assets/2671923/17216593/effe70cc-54a6-11e6-8526-3b51112d93df.png)

**Comment by germanvaleroelizondo** [comment]
Notice that the plugin moved the pre-selected area to the first question I had previously made and offered me that question for editing.

Please reproduce the above issue and comment

**Comment by germanvaleroelizondo** [comment]
Funny,
I saved, accepted the notice that the new version of my question had fewer elements that the previous one (I erased the contents of a previosly made question instead of creating a new question. I saved, re-opened, tried editing a different part of the paragraph and IT WORKED FINE...
I am puzzled, but working on it.

**Comment by germanvaleroelizondo** [comment]
The problem seems to arise when I had previously made one particular question type and inmediatly afterward I block some text further ahead and try to make a similar question type (MULTICHOICE_H right after MULTICHOICE and MULTICHOICE_HS  right after  MULTICHOICE_S .

So it seems to me. Please confirm or deny.

**Comment by germanvaleroelizondo** [comment]
After making the MULTICHOICE_S  I can not create the  MULTICHOICE_HS nor the MULTICHOICE_VS

Please comment.

**Comment by germanvaleroelizondo** [comment]
Clicking on 'Decode and verify the question text' works, but does not cure the issue.

Nor does 'Save chabges and continue editing'

**Comment by germanvaleroelizondo** [comment]
Saving the question and re-openig it for re-editing does work .

**Comment by germanvaleroelizondo** [comment]
And now I can not make the last SHORTANSWER example, because the editor insists in re-editing the previous NUMERICAL example :(

**Comment by dthies** [comment]
I think I thought of this more as a feature rather than a bug, but it is obviously confusing at the moment. The form is cleared if you hit insert or cancel and will ask for new question type again. If you close the window after opening a question it copies it on to the form so takes those values for creating a new question. The advantage of having this is for producing several multichoice questions with the same distractors and feedback. This is expecially useful if you want to create a matching type question.
It might be better to add either a copy or clear button to the form that would enable that.

**Comment by germanvaleroelizondo** [comment]
Thanks for explaining. I will try to illustrate this in the documentation page.

**Comment by dthies** [comment]
I think I know what I should do. I will prevent this from happening, and add a separate button on the chooser to load the previous answers.

**Comment by germanvaleroelizondo** [comment]
That sounds very user-friendly. Thanks

**Comment by germanvaleroelizondo** [comment]
Going home, will continue later...

**Comment by dthies** [comment]
I implemented what I suggested above. A duplicate button in appears which will fill in the values from the previous question that was open as default answers. It would be nice to find a better string to use for the name. The add and delete buttons should now function as expected. with selected text as the default correct answer.

**Comment by germanvaleroelizondo** [comment]
I tested the previous version on a new local 2.7.15 Moodle branch version and it seems to work just as well as in the 3.1.1 Moodle branch :)

I will now test the new version....

**Comment by germanvaleroelizondo** [comment]
Congratulations !

I can confirm that the new version with a 'Duplicate' button behaves exactly as expected. GREAT...

Do you have any more additions to programme into this plugin?

Will you bnow change the version maturity level to beta?

Will you post about it in the Moodle Quiz forum for other Moodlers to download and test ?

I have expanded the documentation page at https://docs.moodle.org/31/en/Cloze_editor_for_Atto and I will now proceed to test all Moodle branches from 2.7 to 3.1 with the same steps. 

These few days have been very productive.

I will be looking forward to this plugin being even more downloaded than the TinyMCE cloze editor is now.

Thanks a lot for having invited me to test your cloze editor for Atto.

**Comment by germanvaleroelizondo** [comment]
ps: Maybe now would be a good time to change the installation instructions for the plugin here in GitHub . Please have a look at my suggested installation intructions in the Moodle Docs page at https://docs.moodle.org/31/en/Cloze_editor_for_Atto

**Comment by germanvaleroelizondo** [comment]
Hi Daniel,
Maybe the 'Duplicate' button can be renamed to 'Add variant' or 'Create variant' ?

**Comment by germanvaleroelizondo** [comment]
Closing this issue, as it seems to have been properly solved.
