### ISSUE TITLE
Another usability addition borrowed from the TinyMCE version.

### ISSUE THREAD

**Issue by germanvaleroelizondo** [dthies/moodle-atto_cloze#4]
Oops... I added a blank paragraph...

**Comment by germanvaleroelizondo** [comment]
When a user blocks some words inside a paragraph and then clicks on the TinyMCE cloze editor button, the blocked text is automatically inserted as the first (correct) option with a 100% correct point.

I think that it would be great if this Atto plugin also had this behaviour.

**Comment by dthies** [comment]
This should be easy.

**Comment by dthies** [comment]
This is a neat feature for creating fill in the blanks. Very cool.

**Comment by germanvaleroelizondo** [comment]
Thanks Daniel. Great improvement. This plugin keeps on improving.

**Comment by germanvaleroelizondo** [comment]
The new version of the plugin works beautifully insering the blocked text as the first correct answer.
