### ISSUE TITLE
Moodle documentation for this plugin

### ISSUE THREAD

**Issue by germanvaleroelizondo** [dthies/moodle-atto_cloze#5]
At https://docs.moodle.org/31/en/Cloze_editor_for_Atto . 
...Work in progress...
Please feel free to add or change as needed.

**Comment by germanvaleroelizondo** [comment]
Some screen grabs were added.
Some text was written.
There are many things to be done.

I will continue tomorrow. I must go somewhere else now.

**Comment by dthies** [comment]
Great work so far on the documentation.

**Comment by germanvaleroelizondo** [comment]
Documentation page at https://docs.moodle.org/31/en/Cloze_editor_for_Atto reasonably complete. I will close this issue now.
