### ISSUE TITLE
 High time to submit for peer testing and review ?

### ISSUE THREAD

**Issue by germanvaleroelizondo** [dthies/moodle-atto_cloze#6]
Hi Daniel.

Great  work you have done in a very short time :)

Will you now post about it in a new thread in the Moodle quiz forum ?
Does your plugin current version comply with the Moodle guidelines for plugin submittal ?
When do you think you can submit it for Moodle plugin approval ?

Thanks a lot for allowing me to collaborate in this process.

**Comment by dthies** [comment]
Hi German,

I am working on adding automated acceptance tests to the plugin. This is preferred by the plugins reviewers and should make testing quicker. Then we should be ready to submit. 
Thank you very much for you help with testing, features and documentation on this plugin. Would you be willing serve as co-maintainer and continue to help with testing and documentation, if so I will make sure you are listed that way in the database.

Daniel

**Comment by germanvaleroelizondo** [comment]
Hi Daniel,

Thanks a lot for your kind offer. I will be very happy to serve as co-maintainer for this plugin.

One question: Did you change the name of the 'Duplicate' button into 'Make variant' or any other string?

I just used the Moodle code tester local plugin on your cloze plugin and I got a few warnings in lib\editor\atto\plugins\cloze\yui\src\button\js\button.js about 'Expected 1 space after "+"; newline found' 

I also got  a warning in line  '#213: ············}
Line indented incorrectly; expected 8 spaces, found 12'

I will download the latest version and  keep on testing Moodle branches 3.0 down to 2.8 in a local server.

It has been a pleasure for me to help you with what I think is a very needed Moodle plugin. 

I think it would be very good if it made it into Moodle core (soon), because many more Moodlers would use the cloze questions if they had this plugin already in place inside the standard Atto editor. Already there are nearly one thousand Moodle servers with the TinyMCE cloze editor currently installed, even though Atto is the standard editor for over 2/3 of all registered Moodle sites (as per Moodle stats). 

Thanks again.

Yurs sincerely,

Germán Valero

**Comment by dthies** [comment]
I have not changed the name yet on duplicate. I would prefer to find a preexisting string in AMOS that is close to what we want so that it works in most locales. Once the plugin is approved in the database, we create modified strings more easily. 
I created a discussion, released beta, and submitted the plugin so it is in the review queue. So I am closing this.
