### ISSUE TITLE
Alternative condition for the button display

### ISSUE THREAD

**Issue by mudrd8mz** [dthies/moodle-atto_cloze#8]
I see the intention is to display the button when and only when the user is actually editing a Cloze question. Alternative and more precise implementation might be to check the body tag's id attribute. When editing such a question, the value is like

```
<body id="page-question-type-multianswer" ... >
```

**Comment by dthies** [comment]
I had thought of that, but am not sure that there is not derivative question type of embedded answer that might also need the editor plugin. I will think about it a little more.
