### ISSUE TITLE
Improve user interface

### ISSUE THREAD

**Issue by dthies** [dthies/moodle-atto_cloze#9]
I pushed some commits to improve the user interface and to implement button hightlighting. After modifiying answer form the affected answer blank is focus. This means saves a mouse click before input and makes it more keyboard friendly. I am not sure whether removing the add and delete buttons entirely is a good idea or not.

**Comment by germanvaleroelizondo** [comment]
I will try this version at home and report back.

**Comment by germanvaleroelizondo** [comment]
No problems seen as of now...

**Comment by dthies** [comment]
When using multiple choice without shuffling, the order of the answers is significant. The interface should provide a way to move answers to a different without forcing teachers in to copy and pasting. I will try adding some buttons to move the items up and down like the filter admin interface.
